from node

RUN apt-get update && \
    apt-get install openssh-server -y && \
    mkdir -p /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo 'root:root' | chpasswd

WORKDIR /root

RUN npm init -y && \
    npm install sequelize pg pg-hstore @faker-js/faker

COPY *.js .

ENTRYPOINT /usr/sbin/sshd -D