from node

RUN apt-get update && \
    apt-get install openssh-server -y && \
    npm init && \
    npm install sequelize pg pg-hstore

RUN mkdir -p /var/run/sshd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    echo 'root:root' | chpasswd

ENTRYPOINT /usr/sbin/sshd -D